### ISSUE TITLE
User can view all product categories

### ISSUE THREAD

**Issue by stevebrownlee** [careless-gazelles/Bangazon-Site#11]
**Given** a user is viewing any page on the Bangazon site
**When** the user performs a gesture on the *Product Categories* hyperlink
**Then** the user will see a view containing a list of all product categories 
**And** next to the category name, the number of products in that category will be displayed
**And** the first three products in the category will be displayed beneath each category, that are hyperlinks to the product detail

##### Sample

```
Electronics (15)
    Dryer
    HD Television
    Sony Walkman

Sporting Goods (7)
    Football
    Ice skates
    Basketball hoop
```

**Comment by krissycaron** [comment]
@megducharme Is this the ProductType/Index page?  And Is this not duplicating the drop down in #12

**Comment by megducharme** [comment]
I was wrong about ticket #12 What he meant in that ticket is that anywhere there is a product category represented (on any page of Bangazon), the category name should be a hyperlink that will take the user to the product category detail page. So, on this view, when the user clicks either Electronics or Sporting Goods, it will take them to that product type's details page. (no dropdown in the nav, only "Product Categories" link.
