### ISSUE TITLE
User can view all products that are of a particular product type

### ISSUE THREAD

**Issue by stevebrownlee** [careless-gazelles/Bangazon-Site#12]
**Given** the user is on any page of the Bangazon site
**When** the user performs a gesture on a product category name
**Then** a list of all products in that category will be displayed, with title, quantity, and price/unit

**Comment by megducharme** [comment]
This does not mean a dropdown in the nav, it simply means that wherever there is a product category listed (on any page on the site), it should be a hyperlink that can be clicked on to take the user to the category's product detail page.
