### ISSUE TITLE
User can complete an order

### ISSUE THREAD

**Issue by stevebrownlee** [careless-gazelles/Bangazon-Site#2]
**Given** the user is authenticated
**And** the user is viewing their open order
**When** the user clicks the *Complete Order* button
**Then** the user should be presented with a view that allows them to select a payment type for the order

**Given** the user selects a payment option
**When** the user clicks the *Done* button  
**Then** the payment type must be added to the order
**And** the user will be presented with a confirmation/thank you screen

**Comment by ollieOsh** [comment]
Ticket #16 allows for viewing of all previous orders -- will keep Index the same.
Need to change 'Details' view to include list of products -- 'Shopping Cart' link will land here.
Add logic to 'Details' to display 'Complete Order' button or 'Order Total' if order is complete.
Need to change 'Create' view to 'Complete' and pass or display entire order - Add 'Done' button to add PaymentTypeId to current order.
Add 'Confirmation' view.

**Comment by ollieOsh** [comment]
Ticket #6 adds 'Delete' button by each product.
@megducharme Does the user need to be able to change the quantity of a product they're ordering?

**Comment by ollieOsh** [comment]
Ticket #13 adds product to cart
